### ISSUE TITLE
[Enhancement] dcos task ssh

### ISSUE THREAD

**Issue by abhay-agarwal** [mesosphere/dcos-cli#298]
I would like to have a way to ssh into the environment of a certain task rather than just a node itself. For example, to ssh in to the environment of any/every elasticsearch node to install plugins etc.

For docker, this would mean using 'docker exec', but for the mesos isolator, this would just be about dropping you in the right folder.

**Comment by mgummelt** [comment]
We discussed this when designing the new CLI commands.  Cody and I were for it, but Thomas thought it didn't make sense because Alice's aren't going to have SSH access.

Take it up with him.

**Comment by abhay-agarwal** [comment]
Weird so what about node ssh? Also that doesn't currently work on AWS.

**Comment by mgummelt** [comment]
Argument was that `node ssh` is for Dan, who does have access, and Dan doesn't care about tasks

**Comment by mgummelt** [comment]
And yea, sucks that it doesn't work on AWS.  It's because the slaves are unroutable from outside the cluster.  We could have added a --bastion=<host> option that would first hop to e.g. the master, but Thomas thought it was just a hack around our lack of a real VPN solution.

You could argue the hack is worth it until we get a VPN solution, but yea, that's how it went.
