### ISSUE TITLE
`dcos config show` breaks when no config exists

### ISSUE THREAD

**Issue by cmaloney** [mesosphere/dcos-cli#449]
1. Install the DCOS CLI
1. Notice you have some cached things and `rm -rf ~/.dcos`
1. do a `dcos config show` to try and figure out how to set the cluster URL
```
$dcos config show

Cannot create file [/home/cody/.dcos/dcos.toml]: [Errno 2] No such file or directory: '/home/cody/.dcos/dcos.toml'
```

Doing a `mkdir ~/.dcos` fixes the error / allows me to run `dcos config set core.dcos_url http://<dcos_url>`

**Comment by jsancio** [comment]
@cmaloney Thanks! This was intentional. The CLI will create `dcos.toml` and the `cache` directory but it doesn't create $DCOS_CONFIG (or `~/.dcos` the default). I could be convinced otherwise :).

I think we decided not to do this in case the user sets $DCOS_CONFIG to something like `/usr/something/.dcos` by accident. Else we would have to do `mkdir -p $DCOS_CONFIG` for this to work in all cases.

cc @tamarrow

**Comment by cmaloney** [comment]
I'd vote for creating it in the default directory by default rather than failing to create a file inside the directory. It's how most command line utilities I use work (Although most programs drop their default config into `~/.config/<name>` nowadays).

At the very least a `dcos config show` / purely read operation shouldn't fail because the config doesn't exist with a can't create error. It should either say something like "config file doesn't exist. To make one do X" or preferrably to me print out that the current config is empty, and if I do a `dcos config set` create the file and put my basic options into.

**Comment by tamarrow** [comment]
I'm in favor of having `dcos config show` give a more helpful error and tell the user the create a dir. What do you think @jsancio ?
